"""Vehicle models for the RAAHAT platform (Phase 8)."""

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class VehicleStatus(str, Enum):
    """Operational status of a vehicle."""
    AVAILABLE = "available"
    EN_ROUTE = "en-route"


class VehicleType(str, Enum):
    """Supported vehicle types."""
    TRUCK = "Truck"
    MINI_TRUCK = "Mini Truck"
    AMBULANCE = "Ambulance"
    EMERGENCY_VEHICLE = "Emergency Vehicle"
    SUPPLY_VAN = "Supply Van"


class Vehicle(BaseModel):
    """A single vehicle in the digital twin fleet."""
    id: str
    current_node: str
    capacity: float = Field(ge=0)
    type: VehicleType
    status: VehicleStatus = VehicleStatus.AVAILABLE

    def model_dump_simple(self) -> dict:
        data = self.model_dump()
        data["type"] = self.type.value
        data["status"] = self.status.value
        return data


class VehicleRecommendationRequest(BaseModel):
    """Request payload for the recommendation system.

    The shortage/resource data is generated by the existing Priority Engine
    / supply monitoring system.
    """
    target_node: str
    resource: str
    required_quantity: float = Field(gt=0)


class RecommendActionRequest(BaseModel):
    """Payload accepted by POST /recommend-action."""
    target_node: str
    resource: str
    required_quantity: float = Field(gt=0)
    priority: Optional[str] = None  # From Priority Engine (e.g. "HIGH")


class ConfirmDispatchRequest(BaseModel):
    """Payload accepted by POST /recommend-action/confirm."""
    vehicle_id: str